# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-06-10 15:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import recognition.models


class Migration(migrations.Migration):

    dependencies = [
        ('recognition', '0002_recognition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recognition',
            name='tree',
            field=models.ForeignKey(null=recognition.models.Tree, on_delete=django.db.models.deletion.CASCADE, to='recognition.Tree'),
        ),
    ]
