# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-06-11 00:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recognition', '0003_auto_20170611_0014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recognition',
            name='tree',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='recognition.Tree'),
        ),
    ]
